### ISSUE TITLE
Laravel 5.1?

### ISSUE THREAD

**Issue by larbous** [Edofre/laravel-fullcalendar#14]
Can I use it with Laravel 5.1?

**Comment by Edofre** [comment]
Hi @lsobral 

Not yet, if I find some time tonight I can add support for laravel 5.*

**Comment by larbous** [comment]
Thanks a lot!

**Comment by Edofre** [comment]
@lsobral you can now use V1.0.10 with Laravel 5.1 :)

**Comment by larbous** [comment]
Thanks for the quick solution.
