### ISSUE TITLE
Call to undefined function Edofre\Fullcalendar\JsExpression()

### ISSUE THREAD

**Issue by shinokada** [Edofre/laravel-fullcalendar#23]
Hi, I just followed the README file.

1. When I run the following, nothing happens.

```
php artisan vendor:publish --tag=config
php artisan vendor:publish --tag=fullcalendar
```

2. When I go to calendar page I get the following error.

> Call to undefined function Edofre\Fullcalendar\JsExpression()

3. The package put the following css and js, but links are not working. How can I modify the link?

```
<h1>Calendar</h1>
<div id='fullcalendar'></div><!-- fullcalendar css -->
<link href="/css/fullcalendar.print.css" rel="stylesheet" media="print">
<link href="/css/fullcalendar.css" rel="stylesheet">
<!-- moment js -->
<script src="/js/moment.js"></script>
<!-- fullcalendar js -->
<script src="/js/fullcalendar.js"></script>
<script src="/js/locale-all.js"></script>
```

**Comment by Edofre** [comment]
Hello @shinokada 

Did you add the ServiceProvider and Facade? After that run the following commands
```
php artisan vendor:publish --tag=config
php artisan vendor:publish --tag=fullcalendar
```
The files should be generated.

**Comment by MeiRct** [comment]
@shinokada There is mistake in the README exmaple, which causes that error.

Assuming you copied the exmaple as is:
Inside `$calendar->setOptions()` method, go to `eventClick` array key, and add `new ` before `\Edofre\Fullcalendar\JsExpression("`, 

Before:
` 'eventClick' => \Edofre\Fullcalendar\JsExpression("`
After:
`'eventClick' => new \Edofre\Fullcalendar\JsExpression("`


@Edofre Please notice I created a pull request for fixing this issue: https://github.com/Edofre/laravel-fullcalendar/pull/24
