### ISSUE TITLE
failing at L5.5

### ISSUE THREAD

**Issue by ultimateBusiness** [Edofre/laravel-fullcalendar#31]
Trying to install at a fresh project with Laravel 5.5 is throwing the following error:

$ composer require edofre/laravel-fullcalendar
Using version ^1.2 for edofre/laravel-fullcalendar
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 4 installs, 0 updates, 0 removals
  - Installing npm-asset/moment (2.18.1): Downloading (100%)
  - Installing npm-asset/jquery (3.2.1): Downloading (100%)
  - Installing npm-asset/fullcalendar (3.4.0): Downloading (100%)
  - Installing edofre/laravel-fullcalendar (V1.2.0): Downloading (100%)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'EdoFre\Fullcalendar\FullcalendarServiceProvider' not found

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

**Comment by Edofre** [comment]
@ultimateBusiness Thanks for letting me know, I tagged a new release and solved the problem. If you install v1.2.1 it should work!

**Comment by ultimateBusiness** [comment]
thx - works - well done ;-)

**Comment by bloukrans** [comment]
Hello,

I'm facing the same problem: 5.5 with v1.2.4 failing to install with unsatisfied npm-asset/fullcalendar

i have fullcalendar 3.8.0 already installed...does this conflict / can be pointed to that?

Thanks,
Holger

**Comment by Edofre** [comment]
@bloukrans Could you dump the full error message?

**Comment by Edofre** [comment]
Did you install the fxp/composer-asset plugin? This plugin enables you to download npm/bower packages through composer.

composer global require "fxp/composer-asset-plugin:^1.4.0”

**Comment by bloukrans** [comment]
inst of asset-plugin has failed, got it right now, thanks

moment, jquery and fullcalendar are now installed twice - once plain once with the asset-plugin. 
can i unify this?
