### ISSUE TITLE
Unknown downloader type on install

### ISSUE THREAD

**Issue by euphoricdev** [Edofre/laravel-fullcalendar#39]
Hi, I am getting this error when I try to install via composer:

[InvalidArgumentException]                                                   
  Unknown downloader type: npm-signature. Available types: git, svn, fossil,   
  hg, perforce, zip, rar, tar, gzip, xz, phar, file, path.

I have the fxp/composer-asset-plugin.

Please advise

**Comment by Edofre** [comment]
Hello,

Hm, I've not seen that error before, apparently there is a bug that has to do with the fxp/composer-asset-plugin, see these links for more information and a fix.

https://stackoverflow.com/questions/49940646/composer-fail-on-update-with-npm-signature-error

https://github.com/fxpio/composer-asset-plugin/issues/321

**Comment by euphoricdev** [comment]
Hi, thanks for that - I did see a different thread on the fxp issue - I tried every prior version from 1.4.0 to see if I could get it going, but still the error with previous versions of that package, so I thought it might be something with yours. So while there is this issue, I am now trying to install manually as a work around, but I'm getting an error:

In ProviderRepository.php line 208:
                                                                     
  Class 'Edofre\Fullcalendar\FullcalendarServiceProvider' not found  
                                                                     
I have taken a copy of your package, uploaded it into the vendor folder, edofre/fullcalendar. I have entered the namespace and autoload settings by putting this line into autoload_namespace.php and autoload_psr4.php:
'Edofre\\Fullcalendar\\' => array($vendorDir . '/edofre/fullcalendar/src'),

I entered in the provider and facade setting into composer.json:
provider:
Edofre\FullcalendarScheduler\FullcalendarSchedulerServiceProvider::class,
facade:
'Fullcalendar' => Edofre\FullcalendarScheduler\Facades\FullcalendarScheduler::class,

i have then run the publish commands:

php artisan vendor:publish --tag=config
php artisan vendor:publish --tag=fullcalendar

and run composer dump-autoload

but I am getting that error with any artisan command, and of course on the page it self.

There is not a huge lot of information out there around manual package install - can you please tell me if you think I have done anything wrong or missed a step?

I am running laravel 5.6 on ubuntu 16.04, composer 1.6.4, artisan installed.

Hoping you can shed some light so I can get going, thanks!

**Comment by euphoricdev** [comment]
]

**Comment by Edofre** [comment]
I'm not sure about manual installs, but if I check my installation I can see you need the following entries in your autoload_classmap.php

```php
'Edofre\\Fullcalendar\\Event' => $vendorDir . '/edofre/laravel-fullcalendar/src/Event.php',
    'Edofre\\Fullcalendar\\Facades\\Fullcalendar' => $vendorDir . '/edofre/laravel-fullcalendar/src/Facades/Fullcalendar.php',
    'Edofre\\Fullcalendar\\Fullcalendar' => $vendorDir . '/edofre/laravel-fullcalendar/src/Fullcalendar.php',
    'Edofre\\Fullcalendar\\FullcalendarServiceProvider' => $vendorDir . '/edofre/laravel-fullcalendar/src/FullcalendarServiceProvider.php',
    'Edofre\\Fullcalendar\\JsExpression' => $vendorDir . '/edofre/laravel-fullcalendar/src/JsExpression.php',
    'Edofre\\Fullcalendar\\JsonEncoder' => $vendorDir . '/edofre/laravel-fullcalendar/src/JsonEncoder.php',
```

And in your autoload_static.php
```php
'Edofre\\Fullcalendar\\Event' => __DIR__ . '/..' . '/edofre/laravel-fullcalendar/src/Event.php',
        'Edofre\\Fullcalendar\\Facades\\Fullcalendar' => __DIR__ . '/..' . '/edofre/laravel-fullcalendar/src/Facades/Fullcalendar.php',
        'Edofre\\Fullcalendar\\Fullcalendar' => __DIR__ . '/..' . '/edofre/laravel-fullcalendar/src/Fullcalendar.php',
        'Edofre\\Fullcalendar\\FullcalendarServiceProvider' => __DIR__ . '/..' . '/edofre/laravel-fullcalendar/src/FullcalendarServiceProvider.php',
        'Edofre\\Fullcalendar\\JsExpression' => __DIR__ . '/..' . '/edofre/laravel-fullcalendar/src/JsExpression.php',
        'Edofre\\Fullcalendar\\JsonEncoder' => __DIR__ . '/..' . '/edofre/laravel-fullcalendar/src/JsonEncoder.php',
```

Not that the directory laravel-fullcalendar is different from your fullcalendar directory, so you should adjust accordingly.

**Comment by euphoricdev** [comment]
Oh thank you so much thats exactly the info I needed - now its working!!
