### ISSUE TITLE
Laravel 5.4

### ISSUE THREAD

**Issue by szizso** [Edofre/laravel-fullcalendar#8]
Hi Edofre!

I'd like to try your callendar ($ composer require edofre/laravel-fullcalendar
) but I've got this error message:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - edofre/laravel-fullcalendar V1.0.6 requires laravel/framework 5.3.* -> satisfiable by laravel/framework[5.3.x-dev, v5.3.0, v5.3.0-RC1, v5.3.1, v5.3.10, v5.3.11, v5.3.12, v5.3.13, v5.3.14, v5.3.15, v5.3.16, v5.3.17, v5.3.18, v5.3.19, v5.3.2, v5.3.20, v5.3.21, v5.3.22, v5.3.23, v5.3.24, v5.3.25, v5.3.26, v5.3.27, v5.3.28, v5.3.29, v5.3.3, v5.3.30, v5.3.4, v5.3.5, v5.3.6, v5.3.7, v5.3.8, v5.3.9] but these conflict with your requirements or minimum-stability.

Best Regards!

**Comment by Edofre** [comment]
Hi @szizso 

This is correct, I did not have time yet to update/test the package for 5.4. I've just added a new release which works for 5.4 as well. If you update to version V1.0.7 it should install correctly.

**Comment by szizso** [comment]
Hi @Edofre!

Thx, but I've got error message too.

Problem 1
    - edofre/laravel-fullcalendar V1.0.7 requires bower-asset/fullcalendar v3.0.1 -> no matching package found.

**Comment by Edofre** [comment]
Do you have the fxp/composer-asset plugin installed?

You can install it using this command:
composer global require "fxp/composer-asset-plugin:^1.2.0”

This will add the fxp composer-asset-plugin and your composer will be able to find the bower-asset/fullcalendar package.
You can find more info on this page: https://packagist.org/packages/fxp/composer-asset-plugin

Let me know if this fixes the problem.

I will update the README this weekend to include the use of fxp/composer-asset-plugin.

**Comment by szizso** [comment]
thx, everything is fine ;)
